#! /usr/bin/python3
import sys, os

proxychainsConfigFile = "/etc/proxychains.conf"
address = ""
port = ""

def changeProxy(host):
	info = host.split(":")
	if len(info) < 2:
		print("Usage: changeProxy <address:port>")
		exit(1)
	global address
	global port
	address = host.split(":")[0]
	port = host.split(":")[1]

	with open(proxychainsConfigFile, "r") as file:
	  lines = file.readlines()
	  if lines[-1] == "socks4 127.0.0.1 9050\n":
	    lines = lines + ["http  " + address + "  " + port]
	  else:
	    lines = lines[:-1] + ["http  " + address + "  " + port]  
	
	with open(proxychainsConfigFile, "w") as file:
	  file.writelines(lines)	

if __name__ == '__main__':
	if len(sys.argv) != 2:
		print("Usage: change_proxy_chain <address:port>")
		exit(1)
	changeProxy(sys.argv[1])
	print("Selected address: " + address)
	print("Selected port: " + port)
	print("Close all Firefox windows to reload proxychains")
